### ISSUE TITLE
Sidebar add extra step using CSS modules

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-by-sample#65]
Update Readme (add appendix)

- Webpackconfig: add css modules support (check other webpack samples).

- Move the styles to local file near the component.

- Require the styles.

Assigned to @ebarriosara (pending to accept invite to join the tema)

**Comment by ebarriosara** [comment]
CSS Modules has been added only for app stylesheets. It is not used for Bootstrap or any other stylesheets in node_modules folder.

It wasn't necessary to move the styles near the component because there is only one stylesheet and one src folder (it is not divided into component folders yet).

Readme has been updated, although I didn't realize that a new appendix was needed. Please, let me know if you want me to change it and add a new appendix.
